export enum ProductCategory {
  ELECTRONICS = "electronics",
  CLOTHING = "clothing",
  BOOKS = "books",
  HOME = "home",
  SPORTS = "sports",
  BEAUTY = "beauty",
  TOYS = "toys",
  FOOD = "food",
  AUTOMOTIVE = "automotive",
  GARDEN = "garden",
  HEALTH = "health",
  JEWELRY = "jewelry",
  MUSIC = "music",
  OFFICE = "office",
  PETS = "pets",
  TOOLS = "tools",
  OTHER = "other",
}
